name = "yoru-gal-server"
main = "src/index.ts"
compatibility_date = "2026-04-03"

[vars]
GEMINI_MODEL = "gemini-2.5-flash-lite"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 20
  period = 60
